export interface SpotifyTrack {
  id: string;
  name: string;
  artist?: string;
  artists?: Array<{ name: string }>;
  popularity: number;
  images?: Array<{ url: string }>;
  external_urls?: { spotify?: string };
  // Optional fields present on some Spotify track objects
  duration_ms?: number;
  preview_url?: string | null;
  album?: {
    name: string;
    release_date: string;
    images: Array<{ url: string }>;
  };
}

export interface SpotifyArtist {
  id: string;
  name: string;
  genres?: string[];
  images?: Array<{ url: string }>;
  external_urls?: { spotify?: string };
  popularity?: number;
  followers?: { total: number } | number;
}

export interface MusicIntelligence {
  mainstreamTaste?: number;
  undergroundTaste?: number;
  artistDiversity?: number;
  recentMusicLover?: number;
  vintageCollector?: number;
  uniqueArtistsCount?: number;
  uniqueAlbumsCount?: number;
  artistLoyalty?: number;
}

export interface SpotifyStats {
  averagePopularity?: number;
  totalTracksAnalyzed?: number;
  uniqueArtistsCount?: number;
  uniqueAlbumsCount?: number;
}

export interface SpotifyUserProfile {
  display_name?: string;
  country?: string;
  followers?: { total: number };
  product?: string;
}

export interface SpotifyData {
  topTracks: SpotifyTrack[];
  topArtists: SpotifyArtist[];
  topGenres: string[];
  musicIntelligence?: MusicIntelligence;
  stats?: SpotifyStats;
  userProfile?: SpotifyUserProfile;
  timeRange?: string;
}

export interface ConcertRecommendation {
  artist: string;
  venue: string;
  city: string;
  date: string;
  matchScore: number;
  reason: string;
  ticketUrl?: string;
}

export interface AIAnalysisRequest {
  spotifyData: SpotifyData;
  userLocation?: string;
  preferences: {
    includeConcerts: boolean;
    includeNewArtists: boolean;
    includePlaylistSuggestions: boolean;
    includeMoodAnalysis: boolean;
  };
}

export interface AIEnhancedInsights {
  concerts: ConcertRecommendation[];
  // New artist discoveries: typically an array of small objects with artist and optional metadata
  newArtists: Array<{ artist: string; genre?: string; song?: string; reason?: string }>;
  // Mood analysis is structured data (may include primaryMood and other details)
  moodAnalysis: { primaryMood?: string; [key: string]: unknown } | string;
  // A longer, human-readable analytic paragraph generated by the AI (4-6 sentences)
  analysisParagraph?: string;
  // A sensitive, speculative one-line life-context sentence (framed as a hypothesis, non-diagnostic)
  lifeContext?: string;
  // Playlist suggestions as an array of simple playlist descriptors
  playlists: Array<{ name: string; description?: string }>;
  funFacts: string[];
}

export interface AIAnalysisResponse {
  summary: string;
  enhanced: AIEnhancedInsights;
  confidence: number;
  timestamp: string;
  featuresUsed?: Record<string, boolean>;
}
